Отредактировал описание задачи calcbits - Лабораторная работа №1. Задание 2. Вариант 1
alexey-malov/oop pull request #31
Opened 2024-09-01 14:20 UTC by zxzmlk

Добавил 3 режима работы программы, примеры запуска и 2 тестовых примера

2024-09-04 20:20 UTC, alexey-malov reviewed
> Вопрос: в старой и обновленной версии задания "В случае некорректных входных данных программа должна выйти с кодом, равным 1". Но на Яндекс контесте если программа возвращает код 1, вместо OK выдается вердикт RE - Runtime Error - "программа завершила работу с ненулевым кодом возврата"

Да, похоже, что для тестирующей системы критично, чтобы программа завершилась с нулевым кодом возврата. Иначе её результаты работы проверяться не будут.

Предлагаю изменить условие задачи, чтобы если программа запущена без параметров, то вернуться она должна с нулевым кодом возврата даже в случае ошибки. Если через командную строку ей было передано число, то при ошибке она должна выйти с ненулевым кодом.

Это будет вынужденный компромисс между возможностью тестирования в системе Яндекс.Contest и адекватным поведением.

2024-09-04 20:25 UTC, alexey-malov commented on tasks/01/README.md
> +В случае некорректных входных данных программа должна выйти с кодом, равным 1, и вывести в стандартный поток вывода «Invalid argument».
Предлагаю дополнить условие так, что если она была запущена без параметров, то должна выйти с нулевым кодом возврата даже в случае ошибки.

2024-09-04 20:31 UTC, alexey-malov requested changes
Нужно добавить уточнения, в каких случаях надо выходить с нулевым кодом возврата

2024-09-04 20:32 UTC, alexey-malov commented on tasks/01/README.md
> +Разработайте приложение **calcbits.exe**, выполняющее подсчет и вывод в output количества единичных битов в байте. Для подсчета единичных битов используйте **операции манипулирования битами**.
Эту длинную строку лучше разбеть на 2 или 3 строки не длиннее 100-120 символов

2024-09-05 16:34 UTC, zxzmlk commented
> Нужно добавить уточнения, в каких случаях надо выходить с нулевым кодом возврата

Добавил

2024-09-09 06:01 UTC, alexey-malov approved these changes
Принято

2024-09-09 06:07 UTC, merged