Отредактировал описание задачи dec2bin - Лабораторная работа №1. Задание 2. Вариант №4
alexey-malov/oop pull request #35
Opened 2024-09-09 10:30 UTC by iskolen

2024-09-09 12:45 UTC, alexey-malov commented on tasks/01/README.md
> +**Формат входных данных**
Лучше оформить подзаголовком 5 уровня. Рекомендую установить расширение Markdown Lint — оно предупреждает, когда bold используется для форматирования нечто, похожено на заголовки.

2024-09-09 12:46 UTC, alexey-malov commented on tasks/01/README.md
> +
Между разделами должна быть ровно одна пустая строка. Рекомендую установить расширение Markdown Lint к Visual Studio Code — оно предупреждает о таких ситуациях.

2024-09-09 12:46 UTC, alexey-malov commented on tasks/01/README.md
> +**Формат выходных данных**
Оформить заголовком 5 уровня. Используйте MarkdownLint

2024-09-09 12:47 UTC, alexey-malov commented on tasks/01/README.md
> +**Примеры**
Оформить заголовком. + Перед заголовком должна быть одна пустая строка. 
Используйте markdown Lint

2024-09-09 12:51 UTC, alexey-malov commented on tasks/01/README.md
> +Ввод
Двоеточие следует ставить после "Ввод" и после "Вывод" во всех примерах

2024-09-09 12:54 UTC, alexey-malov commented on tasks/01/README.md
> +- Если программа запущена без параметров (режим stdin), она должна вывести в стандартный поток вывода «**ERROR**» и завершиться с кодом возврата 0.
Включите в редакторе отображение непечатаемых символов и используйте Markdown Lint. Там должно быть включено правило "No trailing spaces" (не ставить пробелы в конце строки.)

2024-09-09 12:54 UTC, alexey-malov requested changes
Нужно поправить описанные выше замечания

2024-09-09 15:07 UTC, iskolen commented
Возник вопрос по поводу оформления файла. В задании используется несколько примеров, которые обозначены одинаковыми заголовками, например, "Пример 1" в разных разделах. При использовании якорей в Markdown для создания ссылок на эти примеры, возникает проблема с их уникальностью. Подскажите, как правильно оформить навигацию по файлу?
![photo_2024-09-09_18-04-45](https://github.com/user-attachments/assets/00df92db-bc53-4081-9242-91d1e3cb9c12)

2024-09-11 20:45 UTC, alexey-malov reviewed
> Возник вопрос по поводу оформления файла. В задании используется несколько примеров, которые обозначены одинаковыми заголовками, например, "Пример 1" в разных разделах. При использовании якорей в Markdown для создания ссылок на эти примеры, возникает проблема с их уникальностью. Подскажите, как правильно оформить навигацию по файлу?
![photo_2024-09-09_18-04-45](https://github.com/user-attachments/assets/00df92db-bc53-4081-9242-91d1e3cb9c12)

В master-new  я положил конфигурационный файл .markdownlint.json, куда добавил правило, запрещающую эту диагностику только для соседних узлов

2024-09-11 20:49 UTC, alexey-malov commented
Я также добавил этот файл в вашу ветку. Сделайте у себя pull и это предупреждение пропадёт

2024-09-12 21:36 UTC, alexey-malov approved these changes

2024-09-12 21:38 UTC, merged