Отредактировал описание для 2 задачи 2 варианта RemoveExtraSpaces
alexey-malov/oop pull request #63
Opened 2024-10-20 17:34 UTC by rakuzzan

2024-11-03 20:33 UTC, alexey-malov requested changes

2024-11-03 20:33 UTC, alexey-malov commented on tasks/02/README.md
> +
Для этой программы не нужны несколько режимов работы, так как это задание изначально подразумевает обработку всех строк, поступающих в stdin.
Отдельные режимы работы нужны для задач, в которых были какие-то параметры командной строки.

2024-11-03 20:33 UTC, alexey-malov commented on tasks/02/README.md
> +- Если программа запущена без параметров, она должна вывести в стандартный поток вывода «ERROR» и завершиться с кодом возврата 0. Это необходимо для корректного тестирования программы в системе Яндек
В этой программе не может быть некорректных входных данных.

На будущее: если в условии говорится о некорретных входных данных, они должны быть показаны в примерах

2024-11-03 20:33 UTC, alexey-malov commented on tasks/02/README.md
> +
Нужно показать в примере пробелы в начале и конца строки

2024-11-03 22:11 UTC, rakuzzan commented
Обновил описание

2024-11-07 08:35 UTC, alexey-malov approved these changes

2024-11-07 08:39 UTC, alexey-malov approved these changes

2024-11-07 08:40 UTC, merged