Изменил описание задачи fill
alexey-malov/oop pull request #65
Opened 2024-10-20 23:50 UTC by akatobis

2024-11-03 22:07 UTC, alexey-malov commented on tasks/01/README.md
> +  введенная на последней строке
Зачем нужен символ 'e'?
Вводить можно до тех пор, пока не будет встречен символ конца файла.

2024-11-03 22:07 UTC, alexey-malov commented on tasks/01/README.md
> +e
Убрать символ e

2024-11-03 22:07 UTC, alexey-malov commented on tasks/01/README.md
> +e
Убрать символ e

2024-11-03 22:09 UTC, alexey-malov commented on tasks/01/README.md
>  ![fill-example](images/fill-example.png)
Лучше в текстовом виде оформить картинку. Тогда не надо будет решать проблему отображения ресурсов в Яндекс.Contest

2024-11-03 22:10 UTC, alexey-malov requested changes
Есть замечания

2024-11-04 22:43 UTC, akatobis commented
Исправил

2024-11-09 10:59 UTC, alexey-malov approved these changes

2024-11-09 11:05 UTC, merged