Изменил текст задания labirynth
alexey-malov/oop pull request #66
Opened 2024-10-21 00:18 UTC by KirillNaRabote

2024-10-29 04:37 UTC, alexey-malov commented on tasks/01/README.md
>  ![labyrinth-example-2](images/labyrinth-example-2.png)
Нужно добавить примеры в текстовом виде.

2024-10-29 04:46 UTC, alexey-malov requested changes

2024-10-29 04:46 UTC, alexey-malov commented on tasks/01/README.md
> +'#' — стена лабиринта, '.' — путь от 'A' до 'B', ' ' — свободное пространство.
Нужно написать, по какому принципу должен строиться путь, чтобы результат был однозначным.
Например, это не единственный путь, который можно проложить между A и B:

```txt
########
#A...  #
#   .  #
#   .  #
#   B  #
########
```

Возможен и такой, и еще десятки подобных ему:

```txt
########
#A     #
#..    #
# ...  #
#   B  #
########
```

В противном случае придётся писать свой чекер для валидации пути.

2024-10-29 04:54 UTC, alexey-malov reviewed
Замечания по набору тестов:

12. В условие задачи надо добавить, что если ширина или высота лабиринта больше 100, то это ошибка

Нужно добавить лабиринт размером 100*100, в котором пусть идёт зигзагом от одного угла к другому. Это нужно, чтобы отсеять решения, в которых используется рекурсия, и глубина стека будет слишком большой.

Нужно добавить примеры, в которых при наличии нескольких кратчайших путей выбирался бы один по описанным в условии правилам (правила надо описать)

2024-11-16 10:42 UTC, alexey-malov commented on tasks/01/README.md
>  ![labyrinth-example-2](images/labyrinth-example-2.png)
Эти картинки нужно заменить на текстовые представления.
На картинке путь нарушает правило построения "север-юг-запад-восток" в окрестностях точки B. В точку B путь должен входить с востока, а не юга.

Добавить пример в набор тестов.

2024-11-16 10:47 UTC, alexey-malov reviewed
Также удалите из Pull Request каталог .idea

2024-11-16 11:10 UTC, alexey-malov reviewed
> Также удалите из Pull Request каталог .idea 

Удалил сам

2024-11-16 11:14 UTC, alexey-malov reviewed
Принцип "Север-юг-запад-восток" не соблюдается в эталонной программе. Я добавил пример 23, в котором на пути от A до B в эталонном решении направления: Из A идёт путь на юг, а не на север. Вблизи точки B обход препятствия происходит справа, а не слева

Ввод:
```txt
###########
#     #   #
#  #      #
#A #      #
#  #   #  #
#     ## ###
#######    #
#          #
#      ### #
#          #
#       B  #
############
```

Вывод:

```txt
###########                                                                                         
#     #   #                                                                                         
#  #      #                                                                                         
#A #..... #                                                                                         
#. #.  #. #                                                                                         
#.... ##.###                                                                                        
####### .  #                                                                                        
#       ...#                                                                                        
#      ###.#                                                                                        
#         .#                                                                                        
#       B..#  
############
```

Ожидаемый ответ:

```txt
###########
#.... #   #
#. #.     #
#A #..... #
#  #   #. #
#     ##.###
####### .  #
#     ...  #
#     .### #
#     .    #
#     ..B  #
############
```

2024-11-16 11:23 UTC, alexey-malov commented
Также добавьте примеры, проверяющие выбор пути между движением по горизонтали и вертикали для таких путей:

```txt
######
#A   #
#.   #
#.   #
#...B#
######

######
#B...#
#   .#
#   .#
#   A#
######

######
#...B#
#.   #
#.   #
#A   #
######

######
#   A#
#   .#
#   .#
#B...#
######
```

2024-11-17 15:01 UTC, KirillNaRabote commented
> Также добавьте примеры, проверяющие выбор пути между движением по горизонтали и вертикали для таких путей:

тесты 18-21

2024-11-19 05:55 UTC, alexey-malov commented on tasks/01/README.md
>  ![labyrinth-example-2](images/labyrinth-example-2.png)
Картинки по-прежнему не заменены на тексты

2024-11-19 05:58 UTC, alexey-malov requested changes
Я выше писал про замену картинок лабиринта на картинки в текстовом виде (картинки нарушают правило "север-юг-запад-восток"

2024-11-24 19:38 UTC, alexey-malov approved these changes

2024-11-24 19:38 UTC, merged